package dev.kosha.identity.dto

import java.time.OffsetDateTime
import java.util.UUID

// --- Department ---

data class CreateDepartmentRequest(
    val name: String,
    val description: String? = null,
    val parentDeptId: UUID? = null,
)

data class UpdateDepartmentRequest(
    val name: String? = null,
    val description: String? = null,
    val managerUserId: UUID? = null,
    val parentDeptId: UUID? = null,
    val status: String? = null,
    /**
     * When set, toggles the legal-review provider flag. Only GLOBAL_ADMIN
     * is authorised to change this — enforced at the service layer.
     * DEPT_ADMIN sees it as read-only.
     */
    val handlesLegalReview: Boolean? = null,
)

data class DepartmentResponse(
    val id: UUID,
    val name: String,
    val description: String?,
    val managerUserId: UUID?,
    val parentDeptId: UUID?,
    val status: String,
    val handlesLegalReview: Boolean,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
)

// --- User Profile ---

data class CreateUserProfileRequest(
    val keycloakId: UUID,
    val displayName: String,
    val email: String,
    val departmentId: UUID,
    val role: String,
)

/**
 * High-level "create a new user" request. The backend provisions both the
 * Keycloak account and the local user_profile row in one atomic operation.
 *
 * [departmentId] is nullable so the department-scoped endpoint
 * `POST /departments/{id}/users` can accept a body without it — the value
 * comes from the path and the controller injects it. The top-level
 * `POST /users/provision` endpoint requires departmentId and is validated at
 * the service layer.
 *
 * If [temporaryPassword] is null/blank, the backend generates a secure random
 * password and returns it in the response so the admin can share it with the
 * new user.
 */
data class ProvisionUserRequest(
    val displayName: String,
    val email: String,
    val departmentId: UUID? = null,
    val role: String,
    val temporaryPassword: String? = null,
)

/**
 * Response for [ProvisionUserRequest]. Carries the new user's profile plus
 * the temporary password (whether supplied by the admin or generated by the
 * backend). The admin is responsible for sharing the password with the user
 * through a secure channel.
 *
 * The password is returned ONCE at creation time and is not stored anywhere
 * in Kosha's database.
 */
data class ProvisionedUserResponse(
    val user: UserProfileResponse,
    val temporaryPassword: String,
    val mustChangePasswordOnFirstLogin: Boolean,
)

/**
 * Response for an admin-initiated password reset. The temporary password is
 * returned to the admin as a safety net (in case email delivery fails), and
 * also sent to the user via the notification listener. [emailDispatched] is
 * a best-effort flag — the listener runs @Async so the reset endpoint
 * returns before the gateway has actually attempted the send. Treat it as
 * "we queued an email" rather than "it landed in the inbox".
 */
data class PasswordResetResponse(
    val user: UserProfileResponse,
    val temporaryPassword: String,
    val emailDispatched: Boolean,
)

data class UpdateUserProfileRequest(
    val displayName: String? = null,
    val email: String? = null,
    val departmentId: UUID? = null,
    val role: String? = null,
    val status: String? = null,
)

data class UserProfileResponse(
    val id: UUID,
    val keycloakId: UUID,
    val displayName: String,
    val email: String,
    val departmentId: UUID,
    val departmentName: String,
    val role: String,
    val status: String,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
)

// --- Access Group ---

data class CreateAccessGroupRequest(
    val name: String,
    val externalRef: String? = null,
    val departmentId: UUID? = null,
)

data class AccessGroupResponse(
    val id: UUID,
    val name: String,
    val externalRef: String?,
    val departmentId: UUID?,
    val createdAt: OffsetDateTime,
)
